-- ===========================================================================
-- Secrets shared between two parts of our own infrastructure, where neither
-- end is a person.
--
-- The push dispatcher is the first and so far only one: pg_cron has to prove
-- it is us when it calls /api/push/dispatch every minute.
--
-- The value is generated by gen_random_bytes INSIDE the database on purpose.
-- A secret typed into a migration, a terminal or a chat window lives in that
-- transcript for as long as the transcript does, which is longer than the
-- secret should. This one has never been seen by anyone — both ends read it
-- from here, and nothing ever prints it.
--
-- Same posture as push_subscriptions: RLS on, no policies, and the grants
-- revoked, so `authenticated` cannot reach it even in principle. Only the
-- service role, which is server-side and never in a browser.
-- ===========================================================================

create table if not exists public.app_secrets (
  name text primary key,
  value text not null,
  created_at timestamptz not null default now()
);

alter table public.app_secrets enable row level security;

revoke all on public.app_secrets from anon, authenticated;
grant all on public.app_secrets to service_role;

-- on conflict do nothing: re-running must never rotate a live secret, which
-- would silently stop the reminders until both ends were updated.
insert into public.app_secrets (name, value)
values ('push_cron', encode(gen_random_bytes(32), 'hex'))
on conflict (name) do nothing;
