-- ===========================================================================
-- Fire the reminder dispatcher once a minute.
--
-- This is the part that makes a reminder arrive with the app closed. Nothing
-- on the phone is running; Postgres is, so Postgres does the waking.
--
-- Why not Vercel Cron, which would be the obvious home for it: the Hobby plan
-- will not run a job more often than once a day. Per-minute scheduling there
-- means Pro, and this project is not on Pro yet. pg_cron is already part of
-- the database we are paying nothing for, and it is a real scheduler.
--
-- Note there is no secret in this file. The bearer token is read out of
-- public.app_secrets, where it was generated by the database itself and has
-- never been printed anywhere — see 004_app_secrets.sql. A token pasted into a
-- migration would live in the repository's history for good.
-- ===========================================================================

create extension if not exists pg_cron;
create extension if not exists pg_net;

-- Idempotent: unschedule first so re-running this does not stack duplicate
-- jobs that would each fire the dispatcher every minute.
select cron.unschedule('ringbornn-push-dispatch')
where exists (select 1 from cron.job where jobname = 'ringbornn-push-dispatch');

select cron.schedule(
  'ringbornn-push-dispatch',
  '* * * * *',
  $job$
  select net.http_post(
    url := 'https://ringbornn.com/api/push/dispatch',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization',
      'Bearer ' || (select value from public.app_secrets where name = 'push_cron')
    ),
    body := '{}'::jsonb,
    -- Generous, because a cold serverless function has to boot first. pg_net
    -- is asynchronous anyway: this only decides when it gives up waiting for
    -- the reply, not how long the request is allowed to take.
    timeout_milliseconds := 15000
  );
  $job$
);
